fixes #4, redefine ivy cache location

diff --git a/.openshift/action_hooks/start b/.openshift/action_hooks/start
--- a/.openshift/action_hooks/start
+++ b/.openshift/action_hooks/start
@@ -32,16 +32,14 @@ cd "$OPENSHIFT_REPO_DIR"
 echo "$PLAY_COMMAND clean" >> $LOG_FILE
 $PLAY_COMMAND clean &> $LOG_FILE
 
-# check https://github.com/opensas/play-example/issues/4
-# update dependencies
-#echo "$PLAY_COMMAND deps $DEPS_PARAMS" >> $LOG_FILE
-#$PLAY_COMMAND deps $DEPS_PARAMS &> $LOG_FILE
-#
-#if [[ ! $? -eq 0 ]]; then
-#	echo "Error: could not update dependencies"
-#	echo "Error executing '$PLAY_COMMAND $DEPS_PARAMS'"
-#	exit 1
-#fi
+echo "$PLAY_COMMAND deps $DEPS_PARAMS -Divy.home=${OPENSHIFT_TMP_DIR}ivy2/" >> $LOG_FILE
+$PLAY_COMMAND deps $DEPS_PARAMS &> $LOG_FILE
+
+if [[ ! $? -eq 0 ]]; then
+	echo "Error: could not update dependencies"
+	echo "Error executing '$PLAY_COMMAND $DEPS_PARAMS'"
+	exit 1
+fi
 
 export PLAY_LOG_PATH=${OPENSHIFT_LOG_DIR}
 echo "$PLAY_COMMAND start --%$ID $PLAY_PARAMS" >> $LOG_FILE
